import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle, } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import useHandleTransact from "@/hooks/useHandleTransact";
const WalletTransactForm = () => {
    const { amount, type, description, setAmount, setType, setDescription, handleTransact, } = useHandleTransact();
    return (_jsx("div", { className: "flex w-full max-w-sm flex-col gap-6", children: _jsxs(Tabs, { defaultValue: "CREDIT", onValueChange: (value) => setType(value), value: type, children: [_jsxs(TabsList, { children: [_jsx(TabsTrigger, { value: "CREDIT", children: "Credit" }), _jsx(TabsTrigger, { value: "DEBIT", children: "Debit" })] }), _jsx(TabsContent, { value: "CREDIT", children: _jsxs(Card, { children: [_jsxs(CardHeader, { children: [_jsx(CardTitle, { children: "Credit" }), _jsx(CardDescription, { children: "Add money to your wallet" })] }), _jsxs(CardContent, { className: "grid gap-6", children: [_jsxs("div", { className: "grid gap-3", children: [_jsx(Label, { htmlFor: "tabs-demo-name", children: "Amount" }), _jsx(Input, { type: "number", min: 0, title: "Please enter a number with exactly 4 decimal places (e.g., 123.4567)", placeholder: "e.g., 123.4567", required: true, value: amount ?? "", onChange: (e) => setAmount(Number(e.target.value)) })] }), _jsxs("div", { className: "grid gap-3", children: [_jsx(Label, { htmlFor: "tabs-demo-name", children: "Description" }), _jsx(Input, { type: "text", id: "tabs-demo-name", value: description, onChange: (e) => setDescription(e.target.value) })] })] }), _jsx(CardFooter, { children: _jsx(Button, { onClick: handleTransact, children: "Add to wallet" }) })] }) }), _jsx(TabsContent, { value: "DEBIT", children: _jsxs(Card, { children: [_jsxs(CardHeader, { children: [_jsx(CardTitle, { children: "Debit" }), _jsx(CardDescription, { children: "Withdraw money from your wallet" })] }), _jsxs(CardContent, { className: "grid gap-6", children: [_jsxs("div", { className: "grid gap-3", children: [_jsx(Label, { htmlFor: "tabs-demo-current", children: "Amount" }), _jsx(Input, { id: "tabs-demo-current", type: "number", value: amount ?? "", onChange: (e) => setAmount(Number(e.target.value)) })] }), _jsxs("div", { className: "grid gap-3", children: [_jsx(Label, { htmlFor: "tabs-demo-current", children: "Description" }), _jsx(Input, { id: "tabs-demo-current", type: "text", value: description, onChange: (e) => setDescription(e.target.value) })] })] }), _jsx(CardFooter, { children: _jsx(Button, { onClick: handleTransact, children: "Withdraw from wallet" }) })] }) })] }) }));
};
export default WalletTransactForm;
